import fs from 'node:fs';
const cfg = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));
const sites = cfg.sites || [];
const UA = 'Mozilla/5.0 (Linux; Android 9) AppleWebKit/537.36 Chrome/120 Mobile Safari/537.36';
const s = sites.find(x => x.name === process.argv[3]);
const sep = s.api.includes('?') ? '&' : '?';
const g = async (u, h = {}) => { const r = await fetch(u, { headers: h }); return { status: r.status, text: await r.text(), headers: r.headers }; };
const home = JSON.parse((await g(`${s.api}${sep}filter=1`, { 'User-Agent': UA })).text);
const d = JSON.parse((await g(`${s.api}${sep}ac=detail&ids=${encodeURIComponent(home.list[0].vod_id)}`, { 'User-Agent': UA })).text);
const item = d.list[0];
const flags = String(item.vod_play_from).split('$$$');
const groups = String(item.vod_play_url).split('$$$');
const i = flags.findIndex(f => /百度/.test(f));
const pid = (groups[i].split('#')[0] || '').split('$').pop();
const p = JSON.parse((await g(`${s.api}${sep}play=${encodeURIComponent(pid)}&flag=${encodeURIComponent(flags[i])}`, { 'User-Agent': UA })).text);
console.log('play 返回 keys:', Object.keys(p), '| parse:', p.parse, '| url 类型:', Array.isArray(p.url) ? 'array' : typeof p.url);
const arr = Array.isArray(p.url) ? p.url : [p.url];
console.log('url 数组:', arr.map(x => String(x).slice(0, 90)));
const direct = arr.filter(x => typeof x === 'string' && /^https?:/.test(x) && !/127\.0\.0\.1|localhost/.test(x));
console.log('直链候选数:', direct.length);
const target = direct.find(u => /\.(mp4|mkv|m3u8|ts)(#|\?|$)/.test(u)) || direct[0];
if (!target) process.exit(0);
const r = await fetch(target, { headers: { 'User-Agent': p.header['User-Agent'], Range: 'bytes=0-2047' } });
const buf = Buffer.from(await r.arrayBuffer());
console.log('\n取流:', r.status, '| content-type:', r.headers.get('content-type'), '| content-range:', r.headers.get('content-range'), '| 字节数:', buf.length);
console.log('前 32 字节 hex:', buf.subarray(0, 32).toString('hex'));
console.log('前 16 字节 ascii:', JSON.stringify(buf.subarray(0, 16).toString('latin1')));